name: Library

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: erlang:24

    steps:
      - name: Get the source code
        uses: actions/checkout@v3

      - name: Build the library
        run: make

      - name: Run the regression tests
        run: make eunit
